### ISSUE TITLE
[TODO]

### ISSUE THREAD

**Issue by ayankcell** [ayankcell/tiangmas#1]
Berikut ini yang belum diselesaikan dalam pembuatan website Tiangmas.com

- [ ] halaman /portfolio/[slug]
- [ ]  halaman /p/index
- [ ] halaman /berita/[slug]
- [ ] halaman /berita/index
- [ ] SEO di halaman /layanan/index
- [ ] SEO /layanan/[slug]
- [ ] SEO /berita/[slug] & /berita/index
